### ISSUE TITLE
How do I cross build a package for Raspberry Pi if I am on Mac/Linux?

### ISSUE THREAD

**Issue by alextran1502** [vercel/ncc#576]
Hello,

There are some libraries such as `serial-port` or `node-usb` that needed to be built on the target platform to generate the correct binary. How do I cross build a project for Raspberry Pi if I am on Mac/Linux?

Thanks,
Alex

**Comment by styfle** [comment]
Hi Alex,

ncc doesn't compile for a specific target, it bundles javascript from multiple js files into a single js file.

If you have native dependencies, you'll need to use `npm install` or `yarn install` with the correct target arch which it outside the scope of ncc.

See this answer: https://stackoverflow.com/a/45988975/266535

**Comment by kohlerdominik** [comment]
@alextran1502 did you find a solution for this? I'm currently stuck with `serial-port` and the same issue as you. Running `ncc build` in WSL and Github Actions seems to install the wrong binaries. If I build on the RPI, it works fine.

**Comment by alextran1502** [comment]
You will have to build it from the RPI or choose the correct machine
architecture on github action to build it on. If i remember correctly it is
arm64v7

**Comment by kohlerdominik** [comment]
As far as I'm aware there's no native possibility to use arm architecture with github actions yet.

Therefore I used an action using QEMU.
```yaml
name: Build for RPI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.1.1
      with:
        arch: aarch64
        distro: bullseye
        githubToken: ${{ github.token }}
        install: |
          apt-get update
          apt-get install -y ca-certificates curl wget build-essential --no-install-recommends
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs build-essential
        run: |
          npm ci --no-audit
          npm run build
```
